name: nb-portfolio
env:
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: nb-portfolio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          npm install

      - name: Deploy
        run: curl "$deploy_url"